// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// collapseData
NumericMatrix collapseData(List mat_list, StringVector colnames);
RcppExport SEXP openCyto_collapseData(SEXP mat_listSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type mat_list(mat_listSEXP );
        Rcpp::traits::input_parameter< StringVector >::type colnames(colnamesSEXP );
        NumericMatrix __result = collapseData(mat_list, colnames);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
