// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// collapseData
NumericMatrix collapseData(List mat_list, StringVector colnames);
RcppExport SEXP _openCyto_collapseData(SEXP mat_listSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mat_list(mat_listSEXP);
    Rcpp::traits::input_parameter< StringVector >::type colnames(colnamesSEXP);
    rcpp_result_gen = Rcpp::wrap(collapseData(mat_list, colnames));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP unlockNamespace(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_openCyto_collapseData", (DL_FUNC) &_openCyto_collapseData, 2},
    {"unlockNamespace",        (DL_FUNC) &unlockNamespace,        1},
    {NULL, NULL, 0}
};

RcppExport void R_init_openCyto(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
