# Generated by cpp11: do not edit by hand

getTautStringApprox <- function(dataVec) {
  .Call(`_openCyto_getTautStringApprox`, dataVec)
}

collapseData <- function(mat_list, colnames) {
  .Call(`_openCyto_collapseData`, mat_list, colnames)
}

singleDip <- function(x) {
  .Call(`_openCyto_singleDip`, x)
}

solve_LSAP_cpp <- function(mat) {
  .Call(`_openCyto_solve_LSAP_cpp`, mat)
}

tsGates <- function(xVec, modePrior) {
  .Call(`_openCyto_tsGates`, xVec, modePrior)
}

unlockNamespace <- function(env) {
  .Call(`_openCyto_unlockNamespace`, env)
}
