# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTautStringApprox <- function(dataVec) {
    .Call('_openCyto_getTautStringApprox', PACKAGE = 'openCyto', dataVec)
}

collapseData <- function(mat_list, colnames) {
    .Call('_openCyto_collapseData', PACKAGE = 'openCyto', mat_list, colnames)
}

singleDip <- function(x) {
    .Call('_openCyto_singleDip', PACKAGE = 'openCyto', x)
}

tsGates <- function(xVec, modePrior) {
    .Call('_openCyto_tsGates', PACKAGE = 'openCyto', xVec, modePrior)
}

