# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapseData <- function(mat_list, colnames) {
    .Call('openCyto_collapseData', PACKAGE = 'openCyto', mat_list, colnames)
}

