# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapseData <- function(mat_list, colnames) {
    .Call('_openCyto_collapseData', PACKAGE = 'openCyto', mat_list, colnames)
}

